(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 635,
	height: 226,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/635x226_atlas_.jpg?1513590024707", id:"635x226_atlas_"}
	]
};



lib.ssMetadata = [
		{name:"635x226_atlas_", frames: [[0,0,675,276],[0,556,635,240],[0,278,635,276]]}
];


// symbols:



(lib.airplan_bg = function() {
	this.spriteSheet = ss["635x226_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.fee_bg = function() {
	this.spriteSheet = ss["635x226_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.wifi_bg = function() {
	this.spriteSheet = ss["635x226_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.wifi_td = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BF0000").s().p("A6EI7IAAx1MA0JAAAIAAR1g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-166.9,-57.1,333.9,114.4);


(lib.wifi_bg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.instance = new lib.wifi_bg();
	this.instance.parent = this;
	this.instance.setTransform(-317.5,-138);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-317.5,-138,635,276);


(lib.wifi = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AggC7IAAkIIBAAAIAAEIgAgdhxQgMgMAAgTQAAgRAMgMQANgNAQAAQARAAANANQAMANAAARQAAASgMANQgNANgRAAQgQgBgNgNg");
	this.shape.setTransform(52.5,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhXCzIAAllICvAAIAABCIhsAAIAABCIBsAAIAAA/IhsAAIAACig");
	this.shape_1.setTransform(34.6,1.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag9AfIAAg8IB6AAIAAA8g");
	this.shape_2.setTransform(10,6.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AggC7IAAkIIBAAAIAAEIgAgdhxQgMgMAAgTQAAgRAMgMQAMgNARAAQAQAAANANQANANAAARQAAASgNANQgMANgRAAQgQgBgNgNg");
	this.shape_3.setTransform(-7.5,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ABBCzIhBjmIhADmIhBAAIhRllIBDAAIA0DjIBAjjIA3AAIBBDjIAzjjIBDAAIhRFlg");
	this.shape_4.setTransform(-36.9,1.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.6,-32.3,123.2,64.6);


(lib.vipt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// t
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,15.5).s().p("AhuhlIAxAUIBmAAIATgZIAzAkQgDADgEACQgFADgHABIAACaQAAAAgFADQgEADgLADQgKACgQABIAAggIhuAAIAAARIgDAFQgDAEgKAEQgKAEgUAAgAhABBIBuAAIAAhBIhuAAgAhAgJIBuAAIAAg/IhuAAg");
	this.shape.setTransform(-80.5,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,29.6).s().p("AjRDNQAbgZARgiQAPgiAJgmQAJgmACgkIBDAJQgBAGgEACQgEACgKAAIgHAgIgKAhQAOAWATAOQASANAZAIIAAi/Ih8AAIgDgJIDxAAIAZggIANAJIAIgYIAFgZIkXAAQACATgFAQQgGAOgKAJQgKAJgPAAQgKAAgJgFQgHgGgBgKQABgIAFgHQAGgGAHgFQAJgEAJgIQAIgIAGgLQAFgLAAgNIAHAAIAEAOIADAMIBzAAIAAhGIBCAGQAAAFgFADQgEADgKABIAAA0IBzAAIAagZIAtAqQgDADgEABIgLACQgJAKgPALQgOAMgOAJIAZARQgCAFgFACQgFABgJAAIh5AAIAABaIA/AAIAagiIAvAjQgCAEgFACQgFACgJAAIhzAAIAABmIAkACIAqABIAXAAIAeAAIAegBIAaAAIAAAGQgNADgGAMQgHALAAAPIhXAAQg2ABgngJQgkgIgbgXQgbgXgSgpQgOAigZAeQgYAdgmAVg");
	this.shape_1.setTransform(-45.5,-2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,27.2).s().p("AioCyQgJgKgZgDIAAgGIAwAAQAEAAACgCQABgCAAgEIAAhsIgPAHIgQAIQgCAFgDADQgDADgEABIgUg6IAagFIAlgHIAAhkIg7AAIgDgJIA+AAIAAhkIBBAFQgBAFgDADQgEACgLACIAABTIAGAAIAWghIAnAiIAAhlIA7AFQAAAEgDACQgDADgKABIAABBQAZgIAZgKIAugWQAVgKAOgJIAxArQgCACgDABIgGABIgIgBIgJgCQgTAFgZAFIg0AJQgcAEgcACIAAAqQAAAGACADQABACAFABIAOAAIBvAAQAIABAFgBQAGgBAEgFQADgEAGgNIAMgfIAEAAIAAAzQANAEAEADQAFADgBAEQAAAJgGAHQgGAFgPAEQgQACgcAAIhtAAQgbAAgNgDQgOgFgGgLQgGgLABgUIAAgeQgDAEgFACQgEACgJgBIguAAIAABdIBDgOIABAEIgeARIgmAUIAACDQAAAQgEAMQgEANgNAIQgMAIgaADQABgXgJgKg");
	this.shape_2.setTransform(-88.9,-1.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,25.1).s().p("AgZBtIhYAAIgCgJIBaAAIAAiDQgeAygvArQgvAqg9AeIgEgGQAkgcAegjQAegjAXgmQAWgpAOgoIiTAAIgEgJIC5AAIAAhwIBDAGQAAAGgFADQgEADgLACIAABcIBoAAIAdgoIA1ApQgDAEgFACQgEACgKAAIibAAQATAoAeAhQAdAgAjAaQAjAaAkAOIgBAFQgQACgLALQgLAMgGARQgzghglg4Qglg1gWhMIgBAAIAAC9IATAAIAZglIAwAmQgDAFgFACQgFABgJAAIhGAAIAABXIgDAEQgEADgLAEQgIAEgVgBg");
	this.shape_3.setTransform(-132,-1.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,25.2).s().p("Aibi+IA0AVIC6AAIAVgbIA0AnIgHAGQgFACgHABIAAFDIgFAFQgFADgLAEQgKADgSAAIAAgpIjCAAIAAAcIgEAGQgDAEgKAFQgKAEgWABgAhqCMIDCAAIAAiTIjCAAgAhqgQIDCAAIAAiPIjCAAg");
	this.shape_4.setTransform(-174.6,-0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,9.9).s().p("AAwAgQgGgCgFgEQgSgOgegMQgggPgtgLIABgGQBFABAlAHQAnAIAQAKQAQAJgBAKQAAAJgJAFQgIAGgMAAIgMgBg");
	this.shape_5.setTransform(138.8,15.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,22.2).s().p("AjKBQIgDgJIC2AAIAAhQIiKAAIgCgJICMAAIAAg9IBBAGQgBAFgDACQgEADgKACIAAArIBJAAIAaggIAwAhQgDAFgFACQgFABgJAAIh9AAIAABQIBqAAIAagiIAyAjQgDAEgFACQgFACgJAAg");
	this.shape_6.setTransform(171.2,9.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,21.7).s().p("AiuBOIAfAAIApAAQAJgRAIgUIAOglIhSAAIgCgHIDwAAIAZgfIAYAPIAFgVIAEgVIkYAAQABATgGANQgGAOgKAIQgLAHgMAAQgLAAgHgEQgIgGgBgLQABgIAFgHQAFgGAIgEQAJgDAJgIQAIgGAGgLQAGgKABgLIAGAAQAEANACAMIByAAIAAg9IBCAFQAAAGgFACQgEAEgKABIAAArIB0AAIAagaIAsAqQgDADgEABIgLABIgVAUQgMAKgNAIIANAJQgCADgFACQgFABgJAAIixAAIAmAMQgBADgCACQgDABgFAAIgCAAIgEgBQgLAPgQAOQgQAPgTANIBRgCIBegCIgZgTQgMgJgNgHIACgFQAwADAbAMQAcALAMAPQAMAPAAAMQAAALgGAHQgGAGgKABIgHgBIgIgEIgNgSIgRgSIhkAQIiLAVIgFAGQgDADgEAAg");
	this.shape_7.setTransform(171.3,-9.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,6.6).s().p("AAZAjIgHgDQgHgMgLgMQgKgKgNgLQgOgKgNgIIADgEQAlABAUAIQAWAJAKALQAJAKAAAKQAAAKgGAGQgFAGgJAAIgCAAIgEgBg");
	this.shape_8.setTransform(141.1,-8.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,8).s().p("AhGAiQASgKASgMQASgMAPgNQANgOAIgMIAzAcQgCADgDABQgEACgFAAIgEgBIgFAAQgNAHgTAJQgQAJgXAIQgWAIgXAFg");
	this.shape_9.setTransform(116.1,-8.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,21.7).s().p("AjIAyQgHgGAAgJQAAgIAGgGQAFgGAIgEQAMgEAJgJQAJgLAAgOIAHAAIADALIADALIB3AAIAAgxIBCAGQAAAFgFADQgDADgLABIAAAfIB3AAIAZgZIArAnQgDADgEABIgLABQgJAKgOALQgOAKgNAIIgFgEIAFgWIAEgZIkgAAQABAPgFAMQgEAMgJAHQgIAHgNAAQgLAAgHgFg");
	this.shape_10.setTransform(128.1,-17.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,25.1).s().p("AivCtQAcgIAbgMQAcgMAXgOQAXgOAPgNIghAAIAAADQABABgEAEQgDAEgLAEQgKAEgTAAIAAiQIgjAFIgjADIgBgIIAjgHIAkgIIAAgaIAkAPIApgOIAkgPIAAhAIhnAAIgDgJIDGAAIAWgbIArAcQgCAEgFACQgFACgJAAIhaAAIAAArIATgLIARgLIAuAjQgBACgDAAQgDACgEAAIgGgBIgIgCQgYAMgfAKQgeAKghAKIB+AAIATgYIAxAjIgGAFQgEACgGABIAAB+IgFAEQgFADgKADQgKAEgRAAIAAgPIiPAAIAtAiIgFADIgHABIgHAAIgFgCQgUAKgbAJQgbAJggAHQgfAGghADgAhABbIC3AAIAAgmIi3AAgAhAAsIC3AAIAAgkIi3AAgAhAghIAAAhIC3AAIAAgjIipAAg");
	this.shape_11.setTransform(125.2,1.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,23.8).s().p("AChB/QgGgCgGgEQgQgOgegPQgdgOgqgMIACgGIAlACIAgACIAAgSIihAAIAyAlIgFAEIgHABIgGgBIgIgBQgTAJgaAJQgbAJgeAGQgfAGgfADIgDgFQAcgJAbgNQAagMAXgPQAWgOAPgOIgeAAIAAAGIgDAFQgEAFgKADQgKAFgUAAIAAjCIAyAUIC5AAIATgXIAyAjQgCACgEACQgEADgGABIAACIQAAABgFADQgGADgKADQgKACgQAAQAlAFAVAHQAWAIAJAHQAJAJAAAIQgBAJgIAGQgIAFgMAAIgMgBgAhaAlIDBAAIAAglIjBAAgAhagJIDBAAIAAgnIjBAAgAhag5IDBAAIAAgmIjBAAg");
	this.shape_12.setTransform(84,6.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,22.6).s().p("AjPBNIgCgJIC6AAIAAglIhFAAIAAAJIgEAFQgEAEgJADQgKADgSABIAAhtIAwATIBCAAIAAgqIBAAGQAAAFgFADQgFACgKACIAAAYIBFAAIASgXIAyAiQgDADgEACQgFADgGABIAAAzIgFAEQgEADgKADQgKADgRAAIAAgTIhJAAIAAAlIBzAAIAaggIAwAhQgCAFgFACQgEABgKAAgAAVAWIBJAAIAAgvIhJAAgAhcAWIBFAAIAAgvIhFAAg");
	this.shape_13.setTransform(84.6,-15.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,14).s().p("AhrhTIAxAUIBgAAIASgYIAzAjQgCADgEADQgFACgHABIAABvIgEAEQgEAEgLADQgKAEgSAAIAAgWIhnAAIAAALIgDAEQgEAEgJAEQgKAEgUAAgAg9A0IBnAAIAAgzIhnAAgAg9gFIBnAAIAAgxIhnAAg");
	this.shape_14.setTransform(48.5,-14);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,18.9).s().p("AAtBsQgCgJgIgEQgIgGgPgCIAAgHIANAAIAQABIAMAAIAIgBQADAAACgCQAHgGAGgbQAGgbADgvIgPAAQgRAwghApQgfAogzAcIgGgHQAkgdAWgoQAVgnAMgqIgSAAQgSApgjAkQgiAjgvAZIgFgGQAggbAZgiQAZgjAPgjIgQAAQgUAbgaAUQgbAWghASIgFgHQAhgbAWgiQAXgkANgoIg7AAIgCgIIDaAAIAaghIAxAiQgCAEgFACQgFABgJAAIigAAIgLAZIgNAXIB/AAIATgYIAwAkQgCACgFACQgEADgGAAQgEAugFAeQgGAegKAPQgKAPgPAGQgPAGgWgBQABgMgDgIg");
	this.shape_15.setTransform(46.4,6.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,17.7).s().p("AhPBvIAVgEIAegGIAAiNIgsAAIgDgJIAvAAIAAh2IA/AHQAAAEgFADQgEADgKABIAABkIADAAIAVgkIAoAlQgDAEgFACQgFACgJAAIgqAAIAACCIAfgHIAggIIABAFQgTANggATQgdAUgrAYQgBAEgEAEQgDADgDABg");
	this.shape_16.setTransform(27.8,-6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.rf(["#CCCCCC","#333333"],[0,1],0,0,0,0,0,29.6).s().p("ACkDMQgPgHgQgLQgQgMgNgSQgaAUgbAMQgdALgdAHIgDgHQAZgLAZgRQAZgSAWgZQgKgTgHgVQgHgWgFgaIg3AAIgCAWIgBAUQAfAHAMALQANANgBALQAAAKgGAGQgGAGgJABQgFAAgFgCQgEgCgEgFQgBgLgGgLQgEgMgGgKQgEAXgKAUQgJAWgQASQgRASgaAQIgGgGQAWgYAKgbQAKgaADgdQACgdAAgeIgOAAQgDAHgFAEQgEADgGAAQgFABgDgCQgFgCgEgFQAAgQgGgSQgFgQgJgOIAADXIgDADQgDADgKAEQgJADgTAAIAAiyQgKAUgNASQgMATgPAQIgGgGQANgbAKggQAKgfAGgfQAIgiADgiIgvAAIgDgJIA4AAIAAhuIA/AFQgBAFgEADQgEADgKABIAABdIAFAAIAUghIAhAgQgCgLgHgLQgFgKgIgIIADgCIAOACIAKAEIAIgjIAJgmIA0ARQgBAEgEACQgEACgIAAIgTAbIgVAZQAKAHAFAGQAEAHAAAGIAAAAIAIgWIAIgWIAoARIgDgmIgBgnIA+AGQAAAEgDADQgFACgKACQACBCADA5QADA5AKAsIA1AAIAJgNIgGADQgDABgEAAIgHgBIgHgFQgBgIgFgIQgEgGgGgGIgCACQgCAEgDACQgDADgEAAIgPgrIAKAAIANAAIAKgWIAKgXIgFACIgGABIgHgBIgIgGQgBgNgGgNQgHgOgJgJIAEgDIALADIAKACIAIggIAJglIA3ASQgBAEgEACQgEABgIAAIgWAZQgMAOgLALQAMAGAFAFQAEAHACAHIAJgXIAIgWIAyAWQgBAEgEACQgEABgIAAIgeApQgQAVgRASIAWAAIAXgCIgFgPIgHgNIAFgDQAZANALANQALANAAAMQgBAKgGAFQgFAHgIAAQgEAAgDgCIgIgHIAAgKIgCgLIgsASQAUADAJAGQAHAHABAEIgBADIAAADIAFgIIAqAfQgDAEgFACQgEACgJAAIheAAIAIAbIAIAZIANgWIAMgZIA0AcIgEADQgCACgEAAIgDAAIgFgBQgJAPgJANIgUAXQANAOAKAIQAKAGADAAQABAAAAAAQAAAAABAAQAAAAABgBQAAAAABgBIADgEIAHgRIAIgWIAHgVIAEAAIgHBMQAJAKADAFQADAHABAEIgCAHQgCAEgFAEQgFAEgKAAQgKAAgPgHgAA4AfIgEgSIgCgQQgDADgEAAQgDACgFgBQgDAAgFgBQgEAAgDgFIgBgLQgBgGgCgFIgYALIglAQQgBADgDABQgDADgEABIgSgqIANAAIARgBIALgaIAMgfIAAAAQgDADgEACQgEACgEAAIgIgCQgDgBgEgEIAAgEQgDADgEACIgNABIgoAAIAAA/QAgAOANAOQANAQgCAOIBvAAIAAAAgAABhNQgOAWgQAUIArgEIgGgOIgHgNIAFgDQAOAHAKAFQAJAHAGAHIgDgmIgDgpIgGAAQgPAWgRAXg");
	this.shape_17.setTransform(-2,-1.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AWSDSQgGgCgGgDQgRgOgggPQgggPgugKIACgGQBEABAnAHQAnAIAQAKQAQALAAAJQgBAKgIAFQgJAGgLAAIgMgCgACFDNQgPgHgQgLQgQgMgNgSQgZAUgcAMQgbALgfAHIgDgHQAbgLAXgRQAZgSAWgZQgKgTgHgVQgHgWgFgaIg1AAIgCAWIgCAUQAeAHAMALQANANAAALQgBAKgGAGQgGAGgJABQgDAAgEgCQgFgCgEgFQgBgLgFgLQgFgMgIgKQgEAXgJAUQgKAWgQASQgRASgaAQIgGgGQAWgYAKgbQAKgaADgdQADgdAAgeIgPAAQgCAHgFAEQgFADgGAAQgEABgEgCQgFgCgDgFQgBgQgFgSQgGgQgJgOIAADXIgDADQgDADgJAEQgKADgTAAIAAiyQgKAUgNASQgMATgPAQIgGgGQANgbAKggQAKgfAHgfQAHgiAEgiIgwAAIgDgJIA4AAIAAhuIA/AFQgBAFgEADQgEADgKABIAABdIAGAAIATghIAiAgQgDgLgGgLQgGgKgIgIIAEgCIANACIAKAEIAIgjIAJgmIA2ARQgBAEgEACQgDACgJAAIgUAbIgWAZQALAHAEAGQAEAHAAAGIABAAIAIgWIAHgWIAoARIgCgmIgCgnIA/AGQgBAEgDADQgEACgKACQABBCADA5QAEA5AJAsIA1AAIAJgNIgGADQgDABgEAAIgHgBIgHgFQgBgIgEgIQgFgGgGgGIgBACQgDAEgDACQgDADgEAAIgPgrIAKAAIANAAIAKgWIAKgXIgFACIgGABIgHgBIgIgGQgBgNgGgNQgGgOgJgJIADgDIALADIAKACIAIggIAJglIA3ASQgBAEgEACQgDABgJAAIgWAZQgLAOgLALQALAGAFAFQAFAHABAHIAJgXIAIgWIAzAWQgCAEgEACQgEABgIAAIgeApQgQAVgQASIAVAAIAXgCIgFgPIgHgNIAFgDQAaANAKANQALANAAAMQAAAKgGAFQgGAHgIAAQgEAAgDgCIgIgHIAAgKIgCgLIgsASQAUADAJAGQAIAHAAAEIgBADIAAADIAGgIIApAfQgCAEgFACQgFACgJAAIheAAIAIAbIAJAZIANgWIALgZIA0AcIgDADQgDACgDAAIgEAAIgFgBQgIAPgKANIgTAXQAMAOAKAIQAKAGADAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABgBIADgEIAHgRIAIgWIAHgVIAEAAIgGBMQAIAKADAFQAEAHAAAEIgCAHQgCAEgFAEQgFAEgJAAQgLAAgPgHgAAZAgIgDgSIgDgQQgCACgEABQgEACgEgBQgEAAgCgBQgEgBgEgEIgBgLQAAgGgCgFIgbALIgkAPQgCAEgDABQgDADgEABIgSgqIANAAIARgBIAMgaIALgfIAAAAQgDADgEACQgDACgEAAIgIgCQgEgBgDgEIgBgEQgDADgEACIgNABIgoAAIAAA/QAgAOANAOQANAQgBAOIBuAAIAAAAgAgbhMQgRAWgQAUIAtgEIgGgOIgGgNIAEgDQAOAHAJAFQAJAHAFAHIgDgmIgDgpIgGAAQgNAWgQAXgAQoDNQAcgJAcgMQAbgMAXgOQAXgNAQgOIghAAIAAAEQAAABgDADQgEAFgKADQgKAFgUAAIAAiTIgiAFIgjADIgCgHIAkgGIAjgHIAAgaIAlAPIAogOIAngPIAAhBIhqAAIgDgJIDIAAIAXgaIArAbQgDAFgEACQgFACgJgBIhbAAIAAArIAUgKIARgLIAuAiQgCADgDAAQgDABgDABIgHgBIgHgCQgYAMgfAKQgfAKgjAJICBAAIASgXIAyAiIgGADQgEADgHABIAACAIgEADQgFAEgKADQgLADgRABIAAgQIiRAAIAvAiIgFAEIgHABIgGAAIgHgCQgUAKgcAJQgbAJggAGQgfAHghACgASYB6IC4AAIAAgmIi4AAgASYBLIC4AAIAAgkIi4AAgASYgBIAAAfIC4AAIAAgiIirAAgAPeDSQgGgCgFgEQgRgOgdgPQgdgOgqgMIACgGIAlACIAfACIAAgSIijAAIAzAlIgFAEIgHABIgHgBIgHgBQgUAJgaAJQgaAJgfAGQgeAGggADIgDgFQAcgJAbgNQAbgMAWgPQAXgOAOgOIgdAAIAAAGIgEAFQgDAFgLADQgKAFgUAAIAAjCIAzAUIC7AAIASgXIAzAjQgCACgFACQgEADgGABIAACIQAAABgFADQgFADgLADQgKACgQAAQAlAFAWAHQAVAIAJAHQAKAJgBAIQAAAJgIAGQgJAFgMAAIgMgBgALiB4IDCAAIAAgnIjCAAgALiBIIDCAAIAAgnIjCAAgALiAYIDCAAIAAgkIjCAAgAHzC/QgCgJgIgEQgIgGgPgCIAAgHIANAAIAQABIAMAAIAIgBQADAAACgCQAHgGAGgbQAGgbADgxIgPAAQgRAyghApQghAogzAcIgGgHQAkgdAWgoQAXgnAMgsIgSAAQgUArgjAkQgiAjgvAZIgFgGQAggbAZgiQAZgjAPglIgQAAQgUAbgaAWQgbAWghASIgFgHQAhgbAWgkQAXgkANgmIg7AAIgCgIIDcAAIAaghIAxAiQgCAEgFACQgFABgJAAIiiAAIgLAXIgNAXICBAAIATgYIAwAkQgCACgFACQgEADgGAAQgEAwgFAeQgGAegKAPQgKAPgPAGQgPAGgWgBQABgMgDgIgA1MBuIhYAAIgCgJIBaAAIAAiDQgeAygvArQguAqg9AeIgFgGQAkgcAegjQAegjAXgmQAWgpAOgoIiTAAIgDgJIC4AAIAAhwIBFAGQAAAGgEADQgFADgLACIAABcIBoAAIAdgoIA1ApQgCAEgFACQgFACgKAAIibAAQAUAoAdAhQAdAgAjAaQAjAaAkAOIgBAFQgPACgMALQgLAMgGARQgzghglg4Qglg1gWhMIgBAAIAAC9IATAAIAaglIAvAmQgDAFgFACQgFABgJAAIhGAAIAABXIgDAEQgEADgKAEQgLAEgVgBgAqiDNQAbgZAQgjQAQgiAJglQAIgnADgjIBDAJQgBAGgEACQgEACgKAAIgHAgIgKAgQAOAXASANQATAOAZAIIAAi/Ih9AAIgDgJIDzAAIAaggIANAIIAHgXIAGgZIkZAAQABATgFAQQgFAOgKAJQgKAJgPAAQgLAAgIgFQgHgGgBgLQABgHAFgIQAFgGAIgEQAJgEAJgIQAIgIAFgLQAGgMAAgNIAHAAIAEAPIADAMIByAAIAAhHIBFAHQgBAFgEADQgEADgKABIAAA0IByAAIAagaIAtArQgCADgEABIgLACQgKAKgOALQgOALgOAKIAZARQgCAFgFACQgFABgJAAIh5AAIAABZIA/AAIAZghIAwAjQgCAEgFACQgFACgJgBIhzAAIAABnIAkACIApABIAYAAIAdAAIAfgBIAZAAIAAAGQgMADgHALQgGAMAAAPIhXAAQg2AAgngIQgngJgbgWQgbgXgRgpQgPAigYAeQgZAdglAVgAudABIAwAUIBpAAIATgXIAyAiQgCADgFACQgFADgHABIAACcQAAAAgEADQgFADgKADQgKACgRABIAAggIhvAAIAAARIgEAFQgDAEgKAEQgKAEgTAAgAtvCpIBvAAIAAhDIhvAAgAtvBdIBvAAIAAg/IhvAAgAwsCzQgIgLgZgDIAAgFIAwAAQADgBACgCQACgCAAgDIAAhsIgQAHIgQAHQgBAGgDACQgEADgDACIgVg7IAbgEIAlgHIAAhkIg8AAIgCgJIA+AAIAAhlIBAAFQAAAFgEAEQgDACgMABIAABUIAHAAIAVghIAnAiIAAhlIA+AEQAAAFgDACQgEACgJABIAABBQAZgIAYgKIAugVQAVgLAPgIIAwArQgCACgCABIgGAAIgIAAIgJgCQgTAFgZAFIg1AJQgbADgcACIAAAqQAAAGABADQABADAFAAIAPABIBuAAQAIABAGgCQAFAAAEgFQAEgFAFgMIANggIAEAAIgBAzQAOAEAEAEQAEACAAAFQAAAJgGAGQgGAGgQADQgPADgdAAIhtAAQgaAAgPgEQgPgEgFgLQgGgLAAgVIAAgdQgDAEgEABQgFACgJAAIguAAIAABdIBEgPIABAFIgeAQIgnAUIAACEQABAPgFANQgEANgMAHQgNAJgZACQAAgXgJgJgA93izIA0AVIC8AAIAVgbIA0AnIgHAGQgFACgHABIAAFEIgFAEQgFAEgLADQgKAEgSgBIAAgpIjEAAIAAAcIgEAGQgDAFgKAEQgKAEgWABgA9GCXIDEAAIAAiVIjEAAgA9GgFIDEAAIAAiPIjEAAgAXaDCIgDgJIC2AAIAAhRIiKAAIgCgJICMAAIAAg9IBDAFQgBAFgDADQgEADgKACIAAArIBJAAIAaggIAwAhQgDAEgFACQgFACgJAAIh9AAIAABRIBqAAIAaghIAyAjQgDAEgFACQgFABgJAAgAC7BHIAVgEIAegGIAAiNIgtAAIgCgJIAvAAIAAh1IBBAGQAAAEgFADQgEADgKACIAABjIADAAIAVgkIAoAmQgDADgFACQgFACgJAAIgqAAIAACCIAfgHIAggIIABAFQgUANgfAUQgfATgrAYQgBAFgEADQgDADgDABgAX3AAIAfAAIApAAQAJgPAIgUIAOglIhSAAIgCgJIDyAAIAZggIAYAQIAFgWIAEgVIkaAAQABATgGAOQgGAOgKAHQgLAHgMABQgLAAgHgFQgIgFgBgLQABgJAFgGQAFgHAIgDQAJgEAJgHQAIgHAGgKQAGgKABgMIAGAAQAEANACAMIByAAIAAg9IBEAGQAAAFgFADQgEADgKABIAAArIB0AAIAagaIAsArQgDADgEAAIgLABIgVAVQgMAJgNAJIANAJQgCAFgFABQgFACgJAAIizAAIAmAMQgBADgCABQgDACgFAAIgCAAIgEgBQgLAOgQAPQgQAPgTALIBSAAIBfgDIgZgTQgMgJgNgHIACgEQAwADAbAMQAcALAMAOQAMANAAANQAAAKgGAHQgGAGgKABIgHgBIgIgDIgNgSIgRgSIhkAQIiNAVIgFAGQgDACgEABgAQ2gcQATgKASgMQASgNAPgOQAOgNAJgNIAzAcQgCADgDACQgEABgFAAIgEAAIgFAAQgNAJgTAJQgTAJgWAIQgWAHgXAFgAWRgaIgHgDQgHgMgLgMQgLgMgOgLQgNgLgNgHIACgEQAmABAWAIQAWAJAJALQAKAMgBAKQAAAKgFAFQgGAHgJAAIgCAAIgEgBgAFujLIAwAUIBiAAIASgYIA0AjQgDADgEACQgFADgGABIAABwIgFAFQgEAEgKADQgLAEgRAAIAAgXIhqAAIAAALIgDAFQgDAEgKAEQgKAEgTAAgAGbhDIBqAAIAAgyIhqAAgAGbh9IBqAAIAAgyIhqAAgAJzg2IgDgJIC7AAIAAgmIhGAAIAAAJIgDAFQgEAEgJADQgKADgSABIAAhvIAvATIBDAAIAAgqIBBAGQAAAFgEADQgFADgKABIAAAYIBFAAIARgXIAyAiQgCADgFADQgEACgHABIAAA1IgEAEQgEADgKADQgKADgRABIAAgUIhJAAIAAAmIBzAAIAaghIAwAiQgCAEgFACQgFACgJAAgANZhuIBJAAIAAgxIhJAAgALlhuIBGAAIAAgxIhGAAgAQthpQgHgFAAgKQAAgIAGgGQAFgGAIgDQAMgFAJgLQAJgLAAgOIAHAAIADALIADALIB3AAIAAgxIBEAHQAAAEgFADQgDADgLABIAAAfIB3AAIAZgYIArAoQgDADgEABIgLABQgJAKgOALQgOALgNAHIgFgDIAFgXIAEgZIkiAAQABAPgFAMQgEAMgJAIQgIAGgNABQgLAAgHgGg");
	this.shape_18.setTransform(2,-2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// 圖層 2
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.596,1],0,35.5,0,-35.4).s().p("EgxrAFiIAArEMBjXAAAIAALEg");
	this.shape_19.setTransform(1,-1.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_19).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-317,-37.1,636,71);


(lib.frist = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhaCFIAAivIgrAAIgBgGIBHAAIARgWIAcAXQgBACgEACIgJABIggAAIAACoQgBACgGACQgFADgKAAgAgkB9IgBgGIA2AAQgDAAgBgCIgFgGIAAgEIABgGIgBgLIgDgLIgFABIgJAAIAAhIIAcAMIBAAAIAMgPIAdAVIgDADIgHACIAAApIgHAEQgGACgLABIgEAAIAAgLIhGAAIAAAFIgBABIgDADQAQAGAGAHQAHAIAAAGQAAAGgEAEQgDAEgGABIAiAAIAGgWIADgWIAnAKQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgHABIgNAPIgRAPIAWAAIAPgTIAcAUQgBADgDABIgJABgAAQA/IBGAAIAAglIhGAAgAiGBnQAEgMACgNIACgcIABgbIAAglIAeADQAAABAAAAQAAABAAABQgBAAAAAAQAAABgBAAQgDACgFAAIAAAcQAAANgCAPQgCAPgGAOQgFAPgLALgAg0gOIAgACQAAABAAAAQgBABAAABQAAAAgBAAQAAABgBAAQgCACgFAAIAABVIgDACQgBACgFACQgEACgJAAgAgWgBIgCgGIB4AAIAKgNIgFABIgGAAIAAgLIhYAAIAAAFQgBACgFADQgEADgJAAIgFAAIAAhhIAbAMIANAAIAAgeIAcADIgCADQgCABgEABIAAAWIAQAAIAAgeIAdACQgBABAAAAQAAABAAAAQgBABAAAAQgBABAAAAQgBABgFABIAAAWIANAAIAMgPIAcAVIgEADIgGACIAABCIgDACIgHACIAVAPQgBADgDABIgJABgABPgkIAQAAIAAgbIgQAAgAArgkIAQAAIAAgbIgQAAgAAHgkIAQAAIAAgbIgQAAgABPhFIAQAAIAAgbIgQAAgAArhFIAQAAIAAgbIgQAAgAAHhFIAQAAIAAgbIgQAAgAh+hnIgBgGIA4AAIAQgVIAdAWQgBADgDABIgJABg");
	this.shape.setTransform(24.4,3.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ABSBzQgEgGgGgCQgHgDgKgBIAAgEIAjAAQAAAAABAAQABAAAAAAQABAAAAgBQABAAAAAAIABgEIAAjhIAoAEQAAADgCACQgDABgHABIAADWQAAAKgCAIQgDAIgIAFQgIAFgRACQAAgMgDgFgAgxABIgSAAIAABeQgBABgEADQgFADgJAAIgEAAIAAhoIAAAAQgBATgEAWQgDAWgJAVQgIAVgPASIgEgDQAIgXAEgaQAEgaABgbQABgZgBgbIAAhaIAgAMIBFAAIALgOIAcAVIgEADIgHADIAAAyIgDACQgCACgGACQgFACgJAAIAAgMIhMAAIAAATIAAALIgBAMIAaALIAPAAIAAgoIAkADQAAADgDABQgCACgGABIAAAeIAPAAIAJgNIAbASIgEADIgIACIAAA9QAAAIgCAGQgBAGgGAEQgFAEgKABIgBgMQgBgFgDgCQgEgCgFgBIAAgEIAOAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAgBIABgCIAAhEIgSAAIAAB7IgCACQgCACgFACQgGACgKAAgAhZg8IBMAAIAAgwIhMAAgAAkhjIAnADQAAADgCACQgDACgGABIAACRIgCACQgCACgGACQgGACgMAAg");
	this.shape_1.setTransform(-4.4,3.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AhVgoIAgAOIAdAAIACgUIABgVIhuAAIgBgGICaAAIAIgTIAIgVIAGgUIArAPQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABIgEABIgCAAIgCAAQgJAJgMALQgMALgOAKIAzAAIATgXIAiAYQgBACgDACIgKABIhkAAQgHALgKAKIgQAUIBCAAIANgRIAhAYIgFADQgDACgEABIAACHIgDADIgKAEQgHACgLAAIAAgVIhuAAIAAAMIgCADQgCADgHADQgGADgNAAgAg3BpIBuAAIAAgoIhuAAgAg3A7IBuAAIAAgmIhuAAgAg3APIBuAAIAAgkIhuAAgAgzhNQgEgCgDgEQAAgHgDgJQgDgJgFgIQgEgIgGgGIACgCQATAFALAGQALAGAFAHQAEAHAAAHQAAAIgFAFQgFAFgHAAIgHgBg");
	this.shape_2.setTransform(-32.9,3.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ApfDLIAAmUIQiAAICdDJIidDLg");
	this.shape_3.setTransform(0,4.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.8,-26.4,121.7,53);


(lib.feedback = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AByC8IASgkQAqAMAyAXIgRAlQgygYgrgMgAgvC/QArgSAegYIgxAAIAAi1IDdAAIAAC1IiQAAIASAPQggAfg5AdgAARB2ICLAAIAAgYIiLAAgAARBDICLAAIAAgVIiLAAgAARASICLAAIAAgTIiLAAgAjKC1QAIgGAAgKIAAjxICGAAIAAChIhdAAIAABKQAVgGAagOQgFgNgLgSIAlgQQAVAjAVAxIglATQgEgNgEgIQg8AcglAMgAiZAwIAzAAIAAgcIgzAAgAiZgOIAzAAIAAgYIgzAAgAgsg1IAAgiIBtAAIAAgUIhYAAIAAhUIBYAAIAAgZIArAAIAAAZIBbAAIAABUIhbAAIAAAUIBwAAIAAAigABsiIIA0AAIAAgZIg0AAgAAPiIIAyAAIAAgZIgyAAgAjfh/QA6gpAgg3IArAQIgGAJQAjAcAdAgIgaAkQgLgOgKgKIAAAdIhUAAIAAgVQgYAVgTANgAiSiGIA7AAQgOgQgTgOQgNARgNANg");
	this.shape.setTransform(75,1.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACcDUIAAgiIk2AAIAAAiIguAAIAAmnIGRAAIAAGngAiaCGIE2AAIAAktIk2AAgAhlBMIAAi8IDMAAIAAC8gAg6AiIB2AAIAAhoIh2AAg");
	this.shape_1.setTransform(25,1.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOC7QAogTApgrIgtAAIAAj5IA6AAQAHgWAFgUIhOAAIAAgoIDNAAIAAAoIhTAAQgFAYgGASIBNAAIAAD5IiAAAIAbAaQglAqgzAcgABCBWIBdAAIAAgkIhdAAgABCAOIBdAAIAAggIhdAAgABCg2IBdAAIAAggIhdAAgAB3CmIAZggQAnARAoAkIgaAhQglghgpgVgAhBDaIAAgQIhLAAIAAAPIgsAAIAAiVICjAAIAACWgAiMCjIBLAAIAAg4IhLAAgAjeAgQAzgPAigWIgmgRIgOALIgegcQAxgkAjg8IAlALQgCAHgGAKIBVAAIAAAlQgMAUggAlQAtAWAfAWIgRAkQgtgegugYQg0Amg0ATgAiSgzIAtATQAVgUAMgSIg+AAIgQATgAjNh1IAAhCIBRAAQgFgPgIgNIArgJQAKASAEATIBQAAIAAA/IgpAAIAAgXIh4AAIAAAag");
	this.shape_2.setTransform(-25,1.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABgCxIAcABQARAAAEgCQADgDAAgFIAAh7IkqAAIAACvIgsAAIAAjVIGCAAIAACtQAAARgNALQgOALg1ABgAhnCqIAAhkIDOAAIAABkgAg7CHIB2AAIAAgfIh2AAgAiSgQIAAhmIEjAAIAABmgAhkgzIDHAAIAAgfIjHAAgAjSiOIAAgmIDAAAQgEgNgKgSIAqgIQALAWAFARIC5AAIAAAmg");
	this.shape_3.setTransform(-74.6,1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-102.1,-35.2,204.2,70.5);


(lib.fee_t = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAeB2IAKgUQA6AFAjAJIgMAUQgugMgtgCgAiDBuQAwgFAhgKIgqAAIAAhYIgdAGIgKgWQAxgFAVgVIg6AAIAKgxIBBAAIAAgPIhPAAIAAgSIBPAAIAAgOIAaAAIAAAOIAoAAIAAgOIAZAAIAAAOIBGAAIAAAzIhGAAIAAANIBQAAQAAAkgHAFQgGAGgHACIgNABIAABiIh/AAIANANQgvASg0AEgAhCBNICGAAIAAgNIiGAAgAhCAvICGAAIAAgOIiGAAgAhCAQICGAAIAAgMIiGAAgABSgMIgEgMQAQABADgDQADgBABgIIg2AAIAAAPIgZAAIAAgPIg1AAQgEAKgPANICEAAgAgXg1IAtAAIAAgNIgqAAQgBAJgCAEgAhYg1IAmAAIAEgNIgoAAgAAvhUIAsAAIAAgPIgsAAgAgShUIAoAAIAAgPIgoAAg");
	this.shape.setTransform(120,0.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA9B4IALgVQAmAGAXAIIgMATQghgJgbgDgAgsBwQAbgFAXgLIgbAAIAAheICKAAIAABeIhbAAIAJAMQgYAMgpAMgAACBPIBZAAIAAgKIhZAAgAACA2IBZAAIAAgLIhZAAgAACAdIBZAAIAAgMIhZAAgAiEB2QAKgbAFgnIAWAHQgCAjgMAigAhYA8IAUgCQAGAiAAAYIgWADQABgYgFgjgAg7A6IATgFQAIAYABASIgUAFQgCgSgGgYgAiCAZQAXgRAZgqIgmAGIgGgYQAUgQAWg/IAYAKQgRApgTAZIAQgCIALgDQAIgPAIgUIAXAKQgfBDggAjQAMgBATgFQgBgIgFgGIAWgIQAKAXAGAaIgWAIQgBgJgCgEQgtAKgXAEgAgfgIIAAgyICdAAIAAAygABRgZIAWAAIAAgQIgWAAgAAkgZIAVAAIAAgQIgVAAgAgGgZIASAAIAAgQIgSAAgAgZhEIAAgSIA8AAIAAgMIhFAAIAAgVIBFAAIAAgJIAaAAIAAAJIBGAAIAAAVIhGAAIAAAMIA+AAIAAASg");
	this.shape_1.setTransform(89.9,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag9CCIgIgaIAoABIAUgBQAEgBAAgJIAAguIh8AAIAAgaIB8AAIAAgqIhsAAIAAgaIBsAAIAAgoQgrAEg9ACIgIgYQB/gEBagVIAQAWQggAJg/AIIAAAsIBcAAIAAAaIhcAAIAAAqIBtAAIAAAaIhtAAIAAA3QAAAKgHAHQgGAIgIABQgFABgaABIgegBg");
	this.shape_2.setTransform(60,0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag4BtQBIgiAgg1IglAAQgpA1hKAcIgPgWQA9gVAngmIgtAAQgXARgYANIgQgVQAugVAdghIgnAAIAAhoIDAAAIAABoIh7AAQgJAOgIAIICnAAQgBAfgCAfQgDAggCAJQgDAIgFAGQgFAGgIADQgIACgRAAIgXAAIgGgZIAbABQANAAAEgCQADgCACgEIADgcIAEgtIgZAAQgeA/hTArgAhAguICJAAIAAgSIiJAAgAhAhXICJAAIAAgRIiJAAg");
	this.shape_3.setTransform(29.6,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAABVQgxAihKAMIgJgbQBBgIAvgdQgagcgTgqIAYgLQATArAWAWQAYgWASgoIAZAJQgTAqgdAcQAvAfBDAIIgKAaQhMgOgvgigAAegzIATgQQA0ArAbAiIgVARQgeglgvgpgAiCAEQAtgaAhgvIAXANQggAwgxAggAh8hKIAAgZIB0AAQgEgNgJgMIAagIQALARADAQIBtAAIAAAZg");
	this.shape_4.setTransform(0.1,0.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AiCBwQA8giAZgsQgWgZgagTQgJAMgLANIgUgSQApgzAPhOIAaAGQgCAQgFARIBDAAQgCBTgaAzQgbA1hAAngAhQghQAbAXAUASQALgaAFgwIgxAAQgHASgHAPgAAgCDIAAkFIAbAAIAABRQAqAjAgAnIgSAWQgXgfghgeIAACRg");
	this.shape_5.setTransform(-29.9,0.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABdCAIAAgLIi5AAIAAALIgbAAIAAj/IDvAAIAAD/gAhcBdIC5AAIAAjEIi5AAgAgLBIQAPgOARgUQgLgigFg4IhXAAIAAgWIBWAAIAAgXIAZAAQgBAMACALIAhAAQgKgGgPgFIAOgPQAOAFANAIIgMANIAQAAIAAAWIg0AAQACAnAGAWQAMgWAKgfIAWAKQgOAugVAeQACAIADAEQAEAEACAAQACAAADgIQADgIACgSIAUARQgIAsgXAAQgPAAgMgVQgOAQgNAJgAhWA3QArgIAtgRIABAWQgoARguAKgAhLAZIAAg+IBIAAIAAA+gAgzADIAXAAIAAgSIgXAAg");
	this.shape_6.setTransform(-60,0.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABHB/IAAgUIiMAAIAAAUIgdAAIAAj8IDFAAIAAD8gAhFBQICMAAIAAhQIiMAAgAhFgZICMAAIAAhLIiMAAg");
	this.shape_7.setTransform(-89.9,1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAwgEIAYgGQAEAWADAMQAPgSAKgQIAYAKQgQAagZAcQANAiAhAbIgUASQg3gwgKhZgAiEBwQAPgbAGgnQAGgmABhJIgZAAIAAgbIAsAAQgFgRgHgPIAZgIQAJAVAFATIAkAAIAAAbIg4AAIgBAjIAzAAQgBA7gCAoQgCAngDAHQgCAGgHAFQgHAFgXAAIgJAAIgHgaIAaAAQAFAAABgFIADgtIABg7IgZAAQgFBWgaAygAgLBtQAIgGAAgIIAAiAQA3gIAxgVIARAWQgqARg4ALIAABuQARgEAXgJIAHAYQg1AUgSADgAghgwQAmgnANgtIAYAIQgCAKgHAQIBfAAIAAAaIhuAAQgPAVgQASg");
	this.shape_8.setTransform(-120.1,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-137.1,-21.9,274.2,43.9);


(lib.fee_bg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.instance = new lib.fee_bg();
	this.instance.parent = this;
	this.instance.setTransform(-317.5,-138);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-317.5,-138,635,240);


(lib.button = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#666666","#CCCCCC","#666666"],[0,0.282,1],-96,0,96,0).s().p("Au/CgIAAk/Id/AAIAAE/g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-96,-16,192,32);


(lib.bgw = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg.b
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(51,204,255,0.329)","rgba(255,255,255,0)"],[0.11,1],0,41.9,0,-42).s().p("EgxvAGjIAAtFMBjfAAAIAANFg");
	this.shape.setTransform(0,46.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(170));

	// bg.w
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","rgba(255,255,255,0.8)","rgba(255,255,255,0)"],[0,0.529,1],0,87.6,0,-87.4).s().p("EgxvANrIAA7VMBjfAAAIAAbVg");
	this.shape_1.setTransform(0,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(170));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-318.4,-86.5,636.9,175.1);


(lib.airplan_bg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.instance = new lib.airplan_bg();
	this.instance.parent = this;
	this.instance.setTransform(-337.5,-138);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-337.5,-138,675,276);


(lib._5day = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AApCfIANgbQBPAGAuANIgPAbQg+gPg9gEgAixCUQBAgGAtgNIg5AAIAAh3QgUAFgTADIgOgeQBCgGAdgdIhOAAIANhDIBYAAIAAgUIhqAAIAAgYIBqAAIAAgTIAiAAIAAATIA4AAIAAgTIAiAAIAAATIBeAAIAABEIheAAIAAATIBsAAQgBAugIAJQgJAIgKACIgQACIAACFIitAAIARARQg/AZhGAFgAhZBnIC1AAIAAgRIi1AAgAhZA/IC1AAIAAgSIi1AAgAhZAWIC1AAIAAgRIi1AAgABvgSIgGgPQAWABAEgDQAFgDAAgJIhIAAIAAAUIgiAAIAAgUIhIAAQgHAMgTARICzAAgAgfhHIA9AAIAAgTIg5AAQgBALgDAIgAh4hHIA0AAIAFgTIg2AAgABAhyIA7AAIAAgTIg7AAgAgahyIA4AAIAAgTIg4AAg");
	this.shape.setTransform(115.5,32);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AivCUQBzgfAgg/IhpAAIAAhkQgKAHgQAIIgUggQBWguArhGIAmANIgRAXIB5AAIAAAhIgpApIBdAAIAAB7IhhAAIAABMQAAAJALAAIBBAAQAHAAAGgIQAGgIACgjIAkAJQgCAdgGARQgHAQgLAHQgLAIgKAAIgnAAQgjAAgQgBQgPgCgIgKQgIgKAAgNIAAhUIgEAAQggBdiGAhgAARAVIBaAAIAAg5IhVAAQgCAmgDATgAhhAVIBPAAQAFgWgBgjIhTAAgAhlhFIBjAAQAcgXARgSIhjAAQgQASgdAXg");
	this.shape_1.setTransform(75,31.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA8BjQgigkgZg4QgeBniCA+IgUgfQB/g8AahnIiRAAIAAgjICZAAQACgmAAgpIiJAAIAAgkIE1AAIAAAkIiIAAIgDBPICZAAIAAAjIiPAAQAfBiB6BCIgUAfQhCgmgigkg");
	this.shape_2.setTransform(34.5,32.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjBGFQhShBgZhwICxAAQAUAqAiAWQAhAVAmAAQA4AAAngpQAngoAAg/QAAg9gkgnQglgogzAAQgaAAgaAOQgbAOgaAbIiJgeIBrnqIGcAAIAACcIkgAAIgjChQAPgFAPgBQAMgDAOAAQB4AABPBTQBQBPAACAQAACChYBZQhYBYh9AAQhwAAhRhAg");
	this.shape_3.setTransform(-21.6,4.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ABgCrIAAgbIi+AAIAAAbIgmAAIAAlVIEJAAIAAFVgAheBsIC+AAIAAhsIi+AAgAhegjIC+AAIAAhkIi+AAg");
	this.shape_4.setTransform(-74.7,32.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABBgGIAhgIQAFAeAEAQQAUgYAOgXIAgAPQgVAjgiAmQARAuAtAlIgbAYQhLhBgNh5gAizCXQAUgkAJg0QAIg0ABhkIghAAIAAgjIA7AAQgHgZgJgTIAhgLQANAdAHAaIAwAAIAAAjIhMAAIgBAwIBEAAQAABQgDA2QgDA1gEAJQgDAJgJAHQgJAGggAAIgMAAIgKgjIAkAAQAHAAABgGIADg+QADg3AAgaIgiAAQgHB3gjBDgAgPCTQALgHAAgMIAAitQBLgMBCgbIAXAdQg5AYhLAOIAACVQAWgEAggNIAJAhQhIAagYAEgAgthBQA0g2ASg7IAhAKQgEANgKAWICCAAIAAAjIiWAAQgUAdgWAZg");
	this.shape_5.setTransform(-115.4,31.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139.1,-77.9,278.2,155.8);


(lib.freet = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAwBXQgDgHgFgDQgFgDgIAAIAAgDIAcAAIACgBIABgCIAAgvIgjAAIAABJQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgKAEQgGABgGAAIgGAAIAAhSIgiAAQgCAQgGAPQgGAPgLAOQgMAOgTALIgCgBQAMgSAGgUQAGgVACgVQACgWgBgTIAAhVIAmANIBaAAIANgSIAhAYIgEAEIgGACIAACRQAAALgDAHQgDAIgIAGQgJAFgRABQAAgOgDgGgAAXAQIAjAAIAAgwIgjAAgAgogRIAAARIgCAQIAiAAIAAgwIggAAgAAXgkIAjAAIAAgxIgjAAgAgogkIAgAAIAAgxIggAAg");
	this.shape.setTransform(35.8,3.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgvBrQASgKAMgKQANgMAFgOQgDgIgEgIIgHgSIACgBQAEAGAFAEIAJAKIAEgQIACgRIgNAAIAAADIgCADQgDADgGACQgHADgNAAIAAhRIAfANIANAAIAAgdIgxAAIgBgEIAyAAIAAghIAqACQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGADIAAAYIANAAIASgXIAgAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAAAIgIABIgzAAIAAAdIANAAIAMgQIAgAXIgEACIgGACIAAAuIgDACQgDACgHABQgHACgMABIAAgLIgQAAQAAAOgEALQgDAMgGAKQARAHAVADQAUADAVAAIAAADQgKAEgHAIQgGAJgDAMQgWgFgRgGQgRgIgMgLQgLAKgOAIQgQAHgWAFgAAuAJIAPAAIAAguIgPAAgAAAAJIANAAIAAguIgNAAgAhSBsIAAhwQgMAMgOALIgCgBQAIgPAIgTQAIgUAHgZQAHgYAFgXIAsANQAAABAAAAQAAAAgBABQAAAAgBABQAAAAgBABIgGABIgKAWIgKAUIAJAEIgCACIgFACIAACLQgBACgDABIgKAFQgGABgGAAg");
	this.shape_1.setTransform(10.5,3.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABMBsIgHgEQgIgGgOgIQgPgIgVgFIABgDIAPAAIAOAAIAAgIIhFAAIAcAVIgBACIgFAAIgDAAIgEgBQgLAGgPAEQgOAEgRADQgRADgRABIgBgDQAOgEAOgHQAOgHALgHQALgIAIgHIgGAAIgDAEQgCADgIADQgHACgNAAIAAhSIgQADIgSACIgBgBQALgCAJgFIAPgIIAAgBIABAAQAIgFAFgGQAGgFADgGIgQAAIgBAEIgBADIgGACIgHABIgHgBIgIgBIADgQIAEgQIACgNIAeALIAQAAIABgIIAAgLIg2AAIgBgDIA3AAIAAgWIAnAEQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgCABgEAAIAAAOIARAAIAAgWIAoAEQAAAAAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgCACgFAAIAAANIASAAIALgOIAeAUIgDADIgFACIAAAQIgDACIgKADIgSACIAAgIIgUAAIAAATIAfAAIAKgNIAbATIgDADIgFABQgBAKgDAFQgCAHgGACQgGADgKABIAKAFIgDADIgFABIAAA9IgEADIgLADIgMACQAVABANADQAMAEAFAEQAGAEgBAFQAAAFgGAEQgFAEgJAAIgHgBgAgnA+IBQAAIAAgTIhQAAgAgnAoIBQAAIAAgTIhQAAgAgnARIBQAAIAAgRIhQAAgAgigXQgJAHgOAGIAUAHIBMAAIAMgPIASANIgBgIQgBgEgCgDQgDgEgGgBIAAgDIAGAAIAGAAIABAAIABAAIABgDIABgHIggAAIAAAWIgCACIgJADQgHACgNAAIAAgdIgdAAQgFAIgJAHgAgNgyIgEAJIAaAAIAAgTIgTAAIgDAKgAg+g0IgCALIARAAIAEgJIADgKIgVAAIgBAIgAAohAIAUAAIAAgTIgUAAgAgIhLIgBAFIgBAGIATAAIAAgTIgRAAIAAAIg");
	this.shape_2.setTransform(-15.6,3.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhqBrQAXgJAMgNQANgOAGgSQAGgQABgUQgFAFgFABQgGADgGAAIgJAAIAAg9IgPAIQgIAEgIADIgBgCQANgKAMgOQANgPAJgPQAKgRAGgQIAsALQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgCAAgFAAIgFAGIgFAGIAhAAIAQgPIAcAZQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgGACQgJAGgMAGQgLAHgMAFIAqAAIAMgQIAgAWIgDADIgGADIAAAvIgDACQgDACgHADQgIACgMgBIAAgKIgCACIgFABIAAA3QgBAEACABQABABAEAAIAcAAIAGAAQABgBAAAAQABAAAAgBQABAAAAgBQAAAAABgBIAFgKIAIgTIABAAIAAAfQAHADACACQADACgBADQAAAGgDAEQgDAEgHADQgIACgOAAIgeAAQgPgBgIgCQgIgCgDgIQgDgHAAgOIAAg5IgJAAQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgCACgFAAQgBAQgFAOQgFAOgLAMQgKAMgSAJQgRAJgbAGgAAQAJIAfAAIAAgxIgfAAgAgsAJIAdAAIAAgxIgdAAgAgmg/IgRAOIAOAFIAmAAIAGgLIAGgLIAFgLIglAAIgPAOg");
	this.shape_3.setTransform(-41.6,3.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#666666").s().p("AAwBXQgDgHgFgDQgFgDgIAAIAAgDIAcAAIACgBIABgCIAAgvIgjAAIAABJQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgKAEQgGABgGAAIgGAAIAAhSIgiAAQgCAQgGAPQgGAPgLAOQgMAOgTALIgCgBQAMgSAGgUQAGgVACgVQACgWgBgUIAAhUIAmAMIBaAAIANgRIAhAYIgEAEIgGACIAACRQAAAKgDAIQgDAIgIAGQgJAFgRABQAAgOgDgGgAAXAQIAjAAIAAgwIgjAAgAgogRIAAARIgCAQIAiAAIAAgwIggAAgAAXgkIAjAAIAAgwIgjAAgAgogkIAgAAIAAgwIggAAg");
	this.shape_4.setTransform(35.8,4.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#666666").s().p("AgvBrQASgJAMgMQANgLAFgOQgDgIgEgIIgHgSIACgBQAEAGAFAFIAJAJIAEgQIACgRIgNAAIAAADIgCADQgDADgGACQgHADgNAAIAAhRIAfANIANAAIAAgdIgxAAIgBgEIAyAAIAAghIAqACQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGADIAAAYIANAAIASgXIAgAXQgBABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAIgIABIgzAAIAAAdIANAAIAMgQIAgAXIgEACIgGACIAAAuIgDACQgDACgHABQgHACgMAAIAAgKIgQAAQAAAOgEALQgDAMgGAKQARAGAVAEQAUADAVAAIAAADQgKAEgHAIQgGAJgDAMQgWgFgRgGQgRgIgMgLQgLAKgOAIQgQAHgWAGgAAuAJIAPAAIAAgvIgPAAgAAAAJIANAAIAAgvIgNAAgAhSBtIAAhxQgMAMgOALIgCgBQAIgPAIgTQAIgUAHgYQAHgZAFgXIAsANQAAABAAAAQAAAAgBABQAAAAgBABQAAAAgBAAIgGACIgKAWIgKAUIAJAEIgCACIgFACIAACLQgBABgDACIgKAFQgGACgGAAg");
	this.shape_5.setTransform(10.5,4.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#666666").s().p("ABMBsIgHgDQgIgHgOgIQgPgIgVgFIABgEIAPAAIAOABIAAgIIhFAAIAcAVIgBACIgFAAIgDAAIgEgBQgLAGgPAEQgOAFgRACQgRADgRABIgBgDQAOgEAOgHQAOgHALgHQALgHAIgIIgGAAIgDAEQgCADgIADQgHACgNAAIAAhSIgQADIgSACIgBgBQALgDAJgEIAPgIIAAgBIABAAQAIgFAFgGQAGgFADgGIgQAAIgBAEIgBADIgGADIgHAAIgHAAIgIgCIADgQIAEgQIACgNIAeALIAQAAIABgIIAAgKIg2AAIgBgEIA3AAIAAgWIAnADQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgCABgEAAIAAAOIARAAIAAgWIAoADQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgCABgFABIAAANIASAAIALgOIAeAUIgDACIgFADIAAAPIgDADIgKADIgSACIAAgIIgUAAIAAASIAfAAIAKgMIAbATIgDACIgFACQgBAKgDAFQgCAHgGACQgGADgKABIAKAFIgDADIgFABIAAA9IgEADIgLADIgMACQAVABANADQAMAEAFAFQAGADgBAFQAAAGgGADQgFAEgJAAIgHgBgAgnA+IBQAAIAAgTIhQAAgAgnAoIBQAAIAAgTIhQAAgAgnARIBQAAIAAgRIhQAAgAgigXQgJAHgOAGIAUAHIBMAAIAMgPIASANIgBgIQgBgEgCgDQgDgDgGgCIAAgCIAGAAIAGAAIABAAIABgBIABgDIABgHIggAAIAAAWIgCACIgJAEQgHABgNAAIAAgdIgdAAQgFAIgJAHgAgNgzIgEAJIAaAAIAAgSIgTAAIgDAJgAg+g0IgCAKIARAAIAEgJIADgJIgVAAIgBAIgAAohAIAUAAIAAgSIgUAAgAgIhLIgBAFIgBAGIATAAIAAgSIgRAAIAAAHg");
	this.shape_6.setTransform(-15.6,4.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("AhqBrQAXgJAMgNQANgPAGgRQAGgQABgUQgFAFgFACQgGACgGAAIgJAAIAAg9IgPAIQgIAEgIADIgBgCQANgKAMgOQANgPAJgPQAKgRAGgQIAsALQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgCABgFgBIgFAGIgFAGIAhAAIAQgPIAcAZQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgGABQgJAHgMAHQgLAGgMAFIAqAAIAMgQIAgAXIgDACIgGACIAAAwIgDACQgDADgHACQgIACgMAAIAAgLIgCACIgFABIAAA3QgBAEACABQABABAEAAIAcAAIAGAAQABgBAAAAQABAAAAgBQABAAAAgBQAAAAABgBIAFgKIAIgTIABAAIAAAfQAHACACADQADACgBADQAAAGgDAEQgDAEgHADQgIACgOAAIgeAAQgPgBgIgCQgIgDgDgHQgDgHAAgOIAAg5IgJAAQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgCACgFAAQgBAQgFAOQgFAOgLALQgKANgSAJQgRAJgbAFgAAQAJIAfAAIAAgxIgfAAgAgsAJIAdAAIAAgxIgdAAgAgmg/IgRAOIAOAFIAmAAIAGgLIAGgLIAFgMIglAAIgPAPg");
	this.shape_7.setTransform(-41.6,4.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// 圖層 2
	this.instance = new lib.button("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-1,3.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97,-21.1,192,44.5);


// stage content:
(lib._635x226 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_299 = function() {
		/* 在此影格停止
		時間軸會在插入此程式碼的影格停止/暫停。
		亦可用來停止/暫停影片片段的時間軸。
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(299).call(this.frame_299).wait(1));

	// feedback
	this.instance = new lib.feedback("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(216.4,144);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(252).to({_off:false},0).to({y:141,alpha:1},4).wait(44));

	// fee_t
	this.instance_1 = new lib.fee_t("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(216.4,96.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(249).to({_off:false},0).to({alpha:1},3).wait(48));

	// feetd
	this.instance_2 = new lib.wifi_td("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(49.1,120.7,0.001,1,0,0,0,-167.2,0);
	this.instance_2.alpha = 0.898;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(246).to({_off:false},0).to({regX:-166.9,scaleX:1},4).wait(50));

	// free_bg
	this.instance_3 = new lib.fee_bg_1("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(317.5,136);
	this.instance_3.alpha = 0.199;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(233).to({_off:false},0).to({y:131,alpha:1},10).wait(57));

	// wifi
	this.instance_4 = new lib.wifi("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(292.1,53.9);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(132).to({_off:false},0).to({_off:true},125).wait(43));

	// 5day
	this.instance_5 = new lib._5day("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(218.1,74.1);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(132).to({_off:false},0).to({_off:true},125).wait(43));

	// frist
	this.instance_6 = new lib.frist("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(61.9,48);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(129).to({_off:false},0).to({x:105.9},3).to({_off:true},125).wait(43));

	// wifi_td
	this.instance_7 = new lib.wifi_td("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(384,76.6,0.012,1,0,0,0,167,0);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(126).to({_off:false},0).to({scaleX:1},4).to({_off:true},127).wait(43));

	// wifi
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A0BLBQibAAhthuQhthtgBiaQAAibBthsIDNjMQEPkOFeiTQFRiOFxgJQFtgJFZB/QFkCCEbECQAKAGAFAGIAbAZQAUASAHAIICPCRQA1A0AbBEQAcBDAABKQABBKgdBEQgcBDg1A0QhrBsiaABQiYAAhshsIiUiQQisirjghaQjYhXjqAAQjoAAjYBXQjgBbisCsIjODMQhsBtiZAAIgBAAg");
	this.shape.setTransform(476,134.6,0.13,0.13);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmiGjQiuiuAAj1QAAj1CuiuQCtiuD2AAQD1AACuCuQCuCuAAD1QAAD1iuCuQiuCvj1AAQj2AAitivg");
	this.shape_1.setTransform(475.8,151.4,0.13,0.13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},173).to({state:[]},18).to({state:[{t:this.shape_1},{t:this.shape}]},9).to({state:[]},57).wait(43));

	// wifi icon
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("EgiaANbQiMgBhkhkQhkhkAAiMQgBiMBkhjIDejfIASgPQG/msI8jpQIojgJYgNQJUgNIyDIQJCDOHPGWQAhAXAVAWIBjBgIABABIB7B7QBjBjAACNQAACNhjBkQhjBjiNABQiNAAhkhjIiviwQlslYnSiyQnCiunlACQnkACnACzQnQC3lqFdIgFAFIjeDfQhjBjiMAAIgBAAg");
	this.shape_2.setTransform(476,120.6,0.13,0.13);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("A0BLBQibAAhthuQhthtgBiaQAAibBthsIDNjMQEPkOFeiTQFRiOFxgJQFtgJFZB/QFkCCEbECQAKAGAFAGIAbAZQAUASAHAIICPCRQA1A0AbBEQAcBDAABKQABBKgdBEQgcBDg1A0QhrBsiaABQiYAAhshsIiUiQQisirjghaQjYhXjqAAQjoAAjYBXQjgBbisCsIjODMQhsBtiZAAIgBAAg");
	this.shape_3.setTransform(476.4,134.6,0.13,0.13);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AmiGjQiuiuAAj1QAAj1CuiuQCtiuD2AAQD1AACuCuQCuCuAAD1QAAD1iuCuQiuCvj1AAQj2AAitivg");
	this.shape_4.setTransform(476.2,151.4,0.13,0.13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]},122).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]},48).to({state:[]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]},5).to({state:[]},15).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]},12).to({state:[]},54).wait(43));

	// wifi_bg
	this.instance_8 = new lib.wifi_bg_1("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(317.5,138);
	this.instance_8.alpha = 0.898;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(114).to({_off:false},0).to({y:113,alpha:1},8).to({_off:true},135).wait(43));

	// Vip
	this.instance_9 = new lib.vipt("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(316,137.1);
	this.instance_9.alpha = 0.102;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(22).to({_off:false},0).to({y:147.1,alpha:1},7).wait(79).to({startPosition:0},0).to({y:137.1,alpha:0},6).to({_off:true},1).wait(185));

	// freet
	this.instance_10 = new lib.freet("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(316.5,201.8);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(22).to({_off:false},0).to({y:191.8,alpha:1},7).wait(79).to({startPosition:0},0).to({y:201.8,alpha:0},6).to({_off:true},1).wait(185));

	// bg.w
	this.instance_11 = new lib.bgw("synched",17);
	this.instance_11.parent = this;
	this.instance_11.setTransform(316.5,225.7,1,0.322,0,0,0,-1,87.5);
	this.instance_11.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({regX:-4,scaleY:1,x:313.5,y:225,alpha:1,startPosition:28},11).to({_off:true},104).wait(185));

	// bg
	this.instance_12 = new lib.airplan_bg_1("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(317.5,113);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({regX:0.1,regY:0.1,scaleX:0.95,scaleY:0.95,x:317.6,y:113.1},10).to({_off:true},105).wait(185));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(297.5,88,675,276);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;